using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using OnlineBanking.Models;


namespace OnlineBanking.Dao
{
    public class CustomerDao
    {
        private OnlineBankingDbContext db = null;

        //Constructor
        public CustomerDao()
        {
            db = new OnlineBankingDbContext();
        }

        public Customer Detail(int iD)
        {
            return db.Customers.SingleOrDefault(m => m.CustomerId == iD);
        }

        public bool UpdateProfile(int iD, string addRess, string loginPass, string confirmPass, string tranPass, string confirmTranpass)
        {
            var cus = db.Customers.Find(iD);
            if (!string.IsNullOrEmpty(addRess))
            {
                if(cus.Address.Length < 5){
                    return false;
                }
                cus.Address = addRess;
            }
            if (!string.IsNullOrEmpty(loginPass))
            {
                if (loginPass != confirmPass || loginPass.Length < 9)
                {
                    return false;
                }
                cus.LoginPassword = loginPass;
            }
            if (!string.IsNullOrEmpty(tranPass))
            {
                if (tranPass != confirmTranpass || tranPass.Length < 9)
                {
                    return false;
                }
                cus.TransactionPassword = tranPass;
            }
            db.SaveChanges();
            return true;
        }

        public bool UpdateForgotPassword(string eMail, string loginPass)
        {
            try
            {
                var cus = db.Customers.SingleOrDefault(m => m.Email == eMail);
                cus.LoginPassword = loginPass;
                db.SaveChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        public void Send(string eMail, string loginPass)
        {
            try
            {
                StringBuilder Body = new StringBuilder();
                Body.Append("<table style=" + "border: 1px solid #1b9ca0; border-radius: 5px;" + ">");
                Body.Append("<tr>");
                Body.Append("<th style=" + "text - align: center; padding: 10px 20px; color: #1b9ca0" + "><h1>Online Banking</h1></th>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<th><h3>Hello <a>" + eMail + "</a></h3></th>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<td><hr /></td>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<td>Because the password was randomly generated by the system, after you have successfully logged in, change the password for the next login.</td>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<td><br /></td>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<td style=" + "font - size: 1em; " + ">YOUR NEW PASSWORD IS: <span style=" + "font - size: 1.5em; background - color: gray; border - radius: 10px; margin - left: 20px; padding: 5px; color: #1b9ca0" + ">" + loginPass + "</span></td>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<td><br /></td>");
                Body.Append("</tr>");
                Body.Append("<tr>");
                Body.Append("<td>Best regards</td>");
                Body.Append("</tr>");
                Body.Append("<tr style=" + "background - color: #1b9ca0;text-align: center;color: white" + ">");
                Body.Append("<td>");
                Body.Append("</td>");
                Body.Append("</tr>");
                Body.Append("</table>");

                MailMessage mail = new MailMessage();
                mail.To.Add(eMail);
                mail.From = new MailAddress("project.sem.3.fpt@gmail.com");
                mail.Subject = "Tiêu đề của mail được gửi";
                mail.Body = Body.ToString();
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = new System.Net.NetworkCredential("project.sem.3.fpt@gmail.com", "onlinebanking");
                smtp.EnableSsl = true;
                smtp.Send(mail);
            }
            catch (Exception)
            {
            }
        }

        public void BlockCustomer(int iD)
        {
            var cus = db.Customers.Find(iD);
            cus.LockedStatus = false;
            db.SaveChanges();
        }

        public Customer GetByEmail(string eMail)
        {
            return db.Customers.SingleOrDefault(m => m.Email == eMail);
        }

        public int Login(string eMail, string loginPass)
        {
            try
            {
                var result = db.Customers.SingleOrDefault(m => m.Email == eMail);
                var pass = result.LoginPassword;
                bool status = result.LockedStatus;

                if (status) {
                    if (pass == loginPass) {
                        return 1;
                    }
                    else {
                        return 3;
                    }
                }
                else {
                    return 2;
                }
               

            }
            catch (Exception)
            {
                return 3;
            }
        }
    }
}